---
- hosts: Localhost
  tasks:
    - name: Install dependency packages with dnf
      dnf:
        name:
          - gcc
          - gcc-c++
          - python39-devel
          - git
          - python39-pip
          - mariadb-devel
          - cloud-utils-growpart
          - postgresql-devel
          state: present
