---
- hosts:  localhost
  tasks:
    - name: Install dependency packages with apt-get
      apt-get:
        name:
          - gcc
          - gcc-c++
          - python39-devel
          - git
          - python39-pip
          - mariadb-devel
          - cloud-utils-growpart
          - postgresql-devel
        state:  present
